### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Jomik** [nalply/rbts#10]
https://github.com/nalply/rbts/blob/589327d0c01da3540dba16e45d355b30ad503094/package.json#L8
When installing you get `tsc: command not found`, probably due to the above.
https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-install

**Comment by nalply** [comment]
You need to install Typescript first.

**Comment by Jomik** [comment]
I do have typescript installed as a `devDependency`, but the above is an unnecessary step as you already bundle the transpiled js files.
I do not want typescript as a global installation as I use a lot of different versions for different projects.

**Comment by nalply** [comment]
ah okay, maybe I will look at it some time

**Comment by DanielSWolf** [comment]
Has there been any progress on this? I'd love to use this package, but the `install` script results in an error, and our build servers don't have TypeScript installed globally.
